#database 연동 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://127.0.0.1:3306/capstone1 # Database이름 ?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: &{DB_PASSWORD}
  thymeleaf:
    cache: false

  # spring data jpa 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update


api-key:
  chat-gpt: ${CHATGPT_KEY}

# Swagger 비활성화
#springdoc:
#  swagger-ui:
#    enabled: false  # Swagger UI 비활성화
#  api-docs:
#    enabled: false  # API 문서 JSON 비활성화
